[package]
name = "hyper-rustls"
version = "0.6.1"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
webpki-roots = "0.11.0"
rustls = "0.9"

[dependencies.hyper]
version = "0.10"
default-features = false

[dev-dependencies]
log = "0.3"
env_logger = "0.3"
